workflows:
  build-android:
    name: Build Android APK
    environment:
      node: 20
      java: 17
      groups:
        - default
      vars:
        NODE_OPTIONS: --max-old-space-size=4096
    scripts:
      - name: Install dependencies
        script: |
          npm install --ignore-scripts
      - name: Pre-bundle assets
        script: |
          # پاک کردن خروجی قبلی تا مسیر اشتباه cache نشه
          rm -rf android/app/src/main/assets
          mkdir -p android/app/src/main/assets
          # ساخت دستی باندل با مسیر درست
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.ts \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res/
      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
