workflows:
  build-android:
    name: Build Android APK
    environment:
      node: 20
      java: 17
      groups:
        - default
      vars:
        NODE_OPTIONS: --max-old-space-size=4096
    scripts:
      - name: Install dependencies
        script: |
          npm install --ignore-scripts
      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease -PcompileSdkVersion=35 -PbuildToolsVersion=35.0.0
    artifacts:
      - android/app/build/outputs/**/*.apk
