workflows:
  build-android:
    name: Build Android APK
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: |
          cd android || cd ..
          flutter pub get
      - name: Build APK
        script: |
          cd android || cd ..
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
