workflows:
  build-android:
    name: Build Android APK
    environment:
      vars:
        NODE_OPTIONS: --max-old-space-size=4096
      node: latest
      java: 17
      groups:
        - default
    scripts:
      - name: Install dependencies
        script: |
          cd mattermost-mobile
          npm install
      - name: Build APK
        script: |
          cd mattermost-mobile/android
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - mattermost-mobile/android/app/build/outputs/**/*.apk
