name: Build Lite APK (auto SDK setup)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK (stable)
        uses: android-actions/setup-android@v3
        with:
          api-levels: 34
          build-tools: 34.0.0
          components: platform-tools

      - name: Accept SDK Licenses
        run: yes | sdkmanager --licenses || true

      - name: Configure Gradle
        run: chmod +x ./gradlew

      - name: Create vector config
        run: |
          mkdir -p vector-app/src/main/assets
          echo '{ "defaultHomeserverUrl": "https://edu97.ir" }' > vector-app/src/main/assets/vector_config.json

      - name: Build Optimized Debug APK
        run: ./gradlew :vector-app:assembleFdroidDebug -PminifyEnabled=true -PshrinkResources=true --no-daemon --stacktrace

      - name: List APKs
        run: ls -lh vector-app/build/outputs/apk/fdroid/debug || true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Andishe-Lite
          path: vector-app/build/outputs/apk/fdroid/debug/*.apk
